# Generated by Django 5.2.4 on 2025-07-09 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('leito', models.CharField(max_length=10)),
                ('data_admissao', models.DateTimeField()),
                ('data_alta', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('via', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacoes', to='sbarCore.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CVC', 'Cateter Venoso Central'), ('SNE', 'Sonda Nasoenteral'), ('SOG', 'Sonda Orogástrica'), ('VM', 'Ventilação Mecânica'), ('Drenos', 'Drenos'), ('SVD', 'Sonda Vesical de Demora'), ('Shilley', 'Shilley'), ('TOT', 'Tubo Orotraqueal'), ('TQT', 'Traqueostomia'), ('PAI', 'Pressão Arterial Ivansiva')], max_length=10)),
                ('data_insercao', models.DateTimeField()),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('local_insercao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='sbarCore.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('Aparência Geral', 'Aparência Geral'), ('Cabeça_Pescoço', 'Cabeça_Pescoço'), ('Neurológico', 'Neurológico'), ('Respiratório', 'Respiratório'), ('Cardiovascular', 'Cardiovascular'), ('Gastrointestinal', 'Gastrointestinal'), ('Urinário', 'Urinário'), ('Musculoesquelético', 'Musculoesquelético'), ('Tegumentar', 'Tegumentar')], max_length=50)),
                ('achados', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='sbarCore.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SBAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField()),
                ('background', models.TextField()),
                ('assessment', models.TextField()),
                ('recommendation', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbar', to='sbarCore.paciente')),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbars', to='sbarCore.plantao')),
            ],
        ),
    ]
