# Generated by Django 5.2.4 on 2025-07-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbarCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='enfermeiro_responsavel',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
